[workspace]

members = [
    # Linux and Windows tool to inspect and customize the system
    "framework_tool",
    # UEFI tool to inspect and customize the system
    "framework_uefi",
    # Catchall library that we'll probably want to split up further
    "framework_lib",
    # Fork of https://github.com/rust-osdev/uefi-rs/blob/main/uefi-macros
    # To avoid pulling in UEFI dependencies when building for an OS
    "guid_macros",
]

# Don't build UEFI by default. Needs special cargo invocation
default-members = [
    "framework_lib",
    "framework_tool",
]

[profile.release]
lto = true
