# Can't use stable rust yet, since we need to support the UEFI target
# UEFI will be supported in stable, soon.
# Once rust-1.68 is released, we can use stable.
[toolchain]
# 2022-12-26
channel = "nightly-2023-03-18"
components = ["rust-src", "clippy", "rustfmt"]
targets = ["x86_64-unknown-uefi"]
