[package]
name = "framework_uefi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uefi"
path = "src/main.rs"

[profile.release]
lto = true

[dependencies]
redox_uefi_std = "0.1.8"

[dependencies.framework_lib]
path = "../framework_lib"
features = ["uefi"]
default-features = false
