[package]
name = "framework_uefi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uefitool"
path = "src/main.rs"

[dependencies.redox_uefi_std]
git = "ssh://git@github.com/FrameworkComputer/redox_uefi_std.git"
branch = "check-event"

[dependencies.framework_lib]
path = "../framework_lib"
features = ["uefi"]
default-features = false
