[package]
name = "framework_tool"
version = "0.1.0"
edition = "2021"

[features]
default = ["linux"]
linux = ["framework_lib/linux"]
windows = ["framework_lib/windows"]

[dependencies]
env_logger = "0.10.0"
log = { version = "0.4", default-features = true }

[dependencies.framework_lib]
path = "../framework_lib"
default-features = false
