[package]
name = "framework_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0" # TODO: Can update to 1.7.0
# TODO: This doesn't work on:
# - Windows
# - Linux when SecureBoot (Lockdown) is enabled
# Need to use the driver in those cases
redox_hwio = "0.1.6"
libc = "0.2.137"
#clap = { version = "4.0", features = ["derive"] }
nix = "0.25.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
#[target.'cfg(windows)'.dependencies]
[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_SystemServices",
]

