[package]
name = "framework_lib"
version = "0.1.0"
edition = "2021"

[features]
default = ["linux"]
# Linux/FreeBSD
unix = ["std", "cros_ec_driver", "raw_pio", "smbios", "dep:nix"]
linux = ["linux_pio", "unix"]
# Windows does not have the cros_ec driver nor raw port I/O access to userspace
windows = ["std", "smbios", "dep:windows"]
smbios = ["dep:smbios-lib"]
std = ["dep:regex", "dep:num", "dep:num-derive", "dep:num-traits", "dep:clap", "smbios-lib?/std", "dep:lazy_static"]
uefi = ["dep:redox_uefi_std", "dep:redox_dmi", "dep:plain", "raw_pio", "smbios"]
# EC communication via Port I/O on Linux
linux_pio = ["dep:libc"]
# EC communication via raw Port I/O (e.g. UEFI or other ring 0 code)
raw_pio = []
# EC communication via cros_ec driver on Linux
cros_ec_driver = []

[dependencies]
regex = { version = "1.6.0", optional = true } # TODO: Can update to 1.7.0
# TODO: This doesn't work on:
# - Windows
# - Linux when SecureBoot (Lockdown) is enabled
# Need to use the driver in those cases
redox_hwio = { version = "0.1.5", default_features = false }
libc = { version = "0.2.137", optional = true }
clap = { version = "4.0", features = ["derive"], optional = true }
nix = { version = "0.25.0", optional = true }
num = { version = "0.4", optional = true }
num-derive = { version = "0.3", optional = true }
num-traits = { version = "0.2", optional = true }
redox_uefi_std = { version = "0.1.8", optional = true }
redox_dmi = { version = "0.1.5", optional = true }
plain = { version = "0.2.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }

[dependencies.smbios-lib]
git = "ssh://git@github.com/FrameworkComputer/smbios-lib.git"
branch = "no-std"
optional = true
default-features = false
# Local development
#path = "../../smbios-lib"
# After my changes are upstreamed
#version = "0.9.0"

[dependencies.windows]
optional = true
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_SystemServices",
]

