name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup show

    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup show

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings