name: CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      # Test builds on Windows as well
      # Lint and tests don't need to run on other OSes
      matrix:
        os: ['ubuntu-22.04', 'windows-2022']
    env:
      # To allow fetching via ssh-agent on Windows, which allows fetching a private repo
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Rust toolchain
      run: rustup show

    - name: Build library (Linux)
      if: matrix.os == 'ubuntu-22.04'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p framework_lib

    - name: Build Linux tool
      if: matrix.os == 'ubuntu-22.04'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p framework_tool

    - name: Upload Linux App
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v3
      with:
        name: framework_tool
        path: target/debug/framework_tool

    - name: Build library (Windows)
      if: matrix.os == 'windows-2022'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p framework_lib --no-default-features --features "windows"

    - name: Build Windows tool
      if: matrix.os == 'windows-2022'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p framework_tool --no-default-features --features "windows"

    - name: Upload Windows App
      if: matrix.os == 'windows-2022'
      uses: actions/upload-artifact@v3
      with:
        name: framework_tool.exe
        path: target/debug/framework_tool.exe

    - name: Build UEFI application (no ESP)
      run: make -C framework_uefi build/x86_64-unknown-uefi/boot.efi

    - name: Upload UEFI App
      if: matrix.os == 'ubuntu-22.04'
      uses: actions/upload-artifact@v3
      with:
        name: framework.efi
        path: framework_uefi/build/x86_64-unknown-uefi/boot.efi

    - name: Install mtools to build ESP (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get install -y mtools

    - name: Build ESP (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: make -C framework_uefi

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      # To allow fetching via ssh-agent on Windows, which allows fetching a private repo
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Rust toolchain
        run: rustup show

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p framework_lib

  lints:
    name: Lints
    runs-on: ubuntu-22.04
    env:
      # To allow fetching via ssh-agent on Windows, which allows fetching a private repo
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Rust toolchain
      run: rustup show

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -p framework_lib -p framework_tool -- -D warnings
